### PR TITLE
Update to .NET 8 and C# 12

### PR DESCRIPTION
**Pull request by Corniel**
As suggested in #249 , I took the liberty to update the target frameworks to .NET 8 (and for the published packages, .NET 6 is the secondary target), and use C# 12.

While at it, I updated the analyzer and Unit Test dependencies.

### CODE REVIEW

**Comment by Corniel** [comment]
@phmonte I also converted al `namespace` declarations to file scoped ones.

**Review by phmonte — APPROVED** [review]

**Comment by Corniel** [comment]
@phmonte I would expected you to have squach merged the branch, but you did not. Was that on purpose?

**Comment by phmonte** [comment]
The repository had squash disabled, I'll enable it, sorry!
I can do the squash manually.

**Comment by phmonte** [comment]
Done

**Pull request merged**
